version: "3"
services:
  menu:
    container_name: menu
    restart: unless-stopped
    ports: 
      - 80:80
    build: menu
  jackett:
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - "./pi/home/media/jackettconfig:/config"
      - "./pi/storage/transmission/:/downloads"
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Argentina/Buenos_Aires
    image: linuxserver/jackett
  plex:
    container_name: plex
    restart: unless-stopped
    environment:
      - VERSION=latest
      - PUID=1001
      - PGID=1001
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "./pi/home/media/plexconfig/:/config"
      - ./pi/home/nginx/config/keys:/cert_keys
      - "./pi/storage/plexmedialibrary/tv-shows/:/data/tvshows"
      - "./pi/storage/plexmedialibrary/movies/:/data/movies"
      - "./pi/storage/plexmedialibrary/anime/:/data/anime"
      - "./pi/home/media/transcode:/transcode"
    image: plexinc/pms-docker
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - "./pi/home/media/radarrconfig:/config"
      - "./pi/storage/transmission/:/downloads"
      - "./pi/storage/plexmedialibrary/Movies/:/data/movies"
      - "./pi/storage/plexmedialibrary/Anime/:/data/anime"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PGID=1001
      - PUID=1001
    depends_on:
      - jackett
      - transmission
    image: linuxserver/radarr
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PUID=1001
      - PGID=1001
    volumes:
      - "./pi/home/media/sonarrconfig:/config"
      - "./pi/storage/plexmedialibrary/TV Shows/:/data/tv"
      - "./pi/storage/plexmedialibrary/Anime/:/data/anime"
      - "./pi/storage/transmission/:/downloads"
    links:
      - jackett
    depends_on:
      - jackett
      - transmission
    image: linuxserver/sonarr
  transmission:
    container_name: transmission
    restart: unless-stopped
    image: linuxserver/transmission
    ports:
      - 9091:9091
      - 51413:51413/udp
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PUID=1001
      - PGID=1001
    volumes:
      - ./pi/home/media/transmission:/config
      - ./pi/storage/transmission/:/downloads
      - ./pi/storage/transmission/:/watch
